const sources: Array<string> = [
  "ABM en la red (23 de abril de 2013). Plan de negocio. Recuperado de https://www.youtube.com/watch?v=xwBfAEMLpV4",
  "Angulo, L. (2016). Proyectos Formulación y evaluación. México: Alfaomega.",
  "Araujo, D. (2012). Proyectos de inversión, análisis, formulación y evaluación práctica. México: Trillas.",
  "Baca, G. (2006). Evaluación de proyectos. México: Mc Graw Hill, 5ta. Edición",
  "Banco Central de Paraguay. (20 de marzo de 2015). Qué es un presupuesto y cómo se elabora. Recuperado de https://www.youtube.com/watch?v=urfwMXPDJV",
  "Bancoldex (6 de junio de 2014). Cómo hacer un presupuesto. Recuperado de https://www.youtube.com/watch?v=1-tBn7XcVJ",
  "Bancoldex (6 de junio de 2014). Necesidades de financiación. Recuperado de https://www.youtube.com/watch?v=Xu_XXNiVdM",
  "Bañuelos, D. (19 de abril de 2012). ¡Cuidado! Ser empresario tiene sus riesgos, pero permanecer como empleado…todavía más. Recuperado de http://soyfranquicia.blogspot.com/2012/04/cuidado-ser-empresario-tiene-sus.htm",
  "Block, Stanley B.; Hirt, Geoffrey A. (2001). Fundamentos de Gerencia Financiera. México: Mc Graw Hill. Novena edición",
  "Calixto, M. (2014). Las principales causas del fracaso de los negocios en México. Recuperado de https://www.eleconomista.com.mx/empresas/Las-principales-causas-del-fracaso-de-los-negocios-en-Mexico-20141014-0058.htm",
  "Chávez, G. (18 de julio de 2017). Petsy sigue los pasos de Amazon y brinca al offline. Recuperado de https://expansion.mx/tecnologia/2017/07/18/petsy-sigue-los-pasos-de-amazon-y-brinca-al-offlin",
  "EBC Academia. (14 de agosto de 2012). ¿Qué son los estados financieros?. Recuperado de https://www.youtube.com/watch?v=CR8miLg0SI",
  "Fernández, D. (2010).¿Cuánto cuestan tus empleados? Recuperado de http://expansion.mx/emprendedores/2010/07/29/cuanto-te-cuestan-tus-empleado",
  "Fernández, S. (2010). Los proyectos de inversión: evaluación financiera. Costa Rica: Editorial Tecnológica de Costa Rica, 2a. edición",
  "Fischer, L; Espejo, J. (2004). Mercadotecnia. México: Mc Graw Hill, 3ra. Edición",
  "Gallardo, J. (1998). Formulación y evaluación de proyectos de inversión. México: Mc Graw Hill",
  "García, V. (2006). Introducción a las finanzas. México: CECSA",
  "Garza, G. (n.d). Notas técnicas: Licencias y permisos para iniciar una empresa en México",
  "Geldes, R., y Loyola, R. (n.d). Apuntes curso de evaluación de proyectos. Universidad Tecnológica Metropolitana",
  "Girard, L. (11 de julio de 2017). Así puedes fijar una estrategia de precio de un producto. Recuperado de https://www.entrepreneur.com/article/26606",
  "Gitman, Laurence J. (2003). Administración Financiera. México: Pearson. décima edición",
  "Gómez, J. (2001). Formulación y evaluación de proyectos. México: IPN-UPIICSA",
  "González, J. (2009). Manual de fórmulas financieras. México: Alfaomega, 1ra. Edición",
  "González, R. (22 de octubre de 2009). Cómo evaluar proyectos de inversión. Recuperado de https://www.entrepreneur.com/article/26289",
  "Hernández, A., y Hernández A. (2001). Formulación y evaluación de proyectos de inversión. México: ECAFSA, 4ta. edición",
  "Hitt, M., y Porter, L. (2006). Administración. México: Pearson. 9a. edición",
  "Industria Alimenticia. (28 de octubre de 2016). Planta embotelladora Coca-Cola FEMSA Tocancipá. Recuperado de https://www.youtube.com/watch?v=C7jJdf8uZv",
  "Johnson, R.W., y Melicher, R.W. (2005). Administración Financiera. México: CECSA, 5a edición",
  "Kotler, P. Marketing 3.0. Recuperado de https://www.youtube.com/watch?v=6rxj8pGPxZ",
  "Lamb, C; et al. (2002). Marketing. México: Thomson Editores, sexta edición",
  "Ley del Impuesto Sobre la Renta (ISR) 2017",
  "Luna, G. (n.d). Tablas de amortización con anualidades vencidas. Recuperado de https://es.coursera.org/lecture/matematicas/tabla-de-amortizacion-con-anualidades-vencidas-UrHK",
  "Merca2.0. (24 de mayo de 2015). 4 productos que se hicieron famosos por accidente. Recuperado de https://www.merca20.com/4-productos-que-se-hicieron-exitosos-por-accidente",
  "Mercado, S. (2011). Administración aplicada, teoría y práctica. México: Limusa",
  "Moyer, et al. (2005). Administración financiera contemporánea. CENGAGE, learning",
  "Münch, L., y García, J. (2020). Fundamentos de administración. México: Trillas",
  "Murcia, J; et al (2010). Proyectos, formulación y criterios de evaluación. México: Alfaomega",
  "Nacional Financiera (n.d). ¿Qué tipo de sociedad mercantil me conviene según mi actividad? Recuperado de https://es.scribd.com/document/36536945/SOCIEDAD-MERCANTIL-",
  "Nacional Financiera. (2001). Guía para la formulación y evaluación de proyectos de inversión. México: Nacional Financiero 9a. Reimpresión",
  "Oppenheimer, A. (n.d). La importancia de la innovación. Recuperado de https://www.youtube.com/watch?v=NwTcLkLy7l",
  "Pérez, A. (26 de marzo de 2017). Demostración de punto de equilibrio para varios productos o mezcla de productos. Recuperado de https://www.youtube.com/watch?v=5KGXQogid5",
  "Pineda, G. (27 de mayo de 2017). Calcular tasa Interna de retorno (TIR) manualmente. Recuperado de https://www.youtube.com/watch?v=96A1zecoGjg&feature=youtu.b",
  "Rivera, F., y Hernández, G. (2010). Administración de Proyectos. México: Pearson",
  "Salazar, J. (2007). Cómo iniciar una pequeña empresa. México: Grupo Editorial Patria",
  "Sapag, N. (2007). Proyectos de inversión formulación y evaluación. México: Pearson",
  "Taylor, J. (1998). Economía. México: CECSA",
  "Tendencias 2020 Coca Cola. Recuperado de https://www.youtube.com/watch?v=D89wnz2XLz",
  "Tipos de distribución de Planta. Recuperado de https://www.youtube.com/watch?v=meEjWAS2S-",
  "UNAM (2014). Panorama de la sociedad 2014 México Indicadores sociales. Revista Perseo. Recuperado de http://www.pudh.unam.mx/perseo/panorama-de-la-sociedad-2014-mexico-indicadores-sociales",
  "Wolf, N. (n.d). Análisis Foda. Recuperado de https://es.coursera.org/lecture/introduccionalaestrategia/matriz-foda-mGMU",
  "Zwilling, M. (n.d). 10 razones por las que fallamos al emprender. Recuperado de https://www.entrepreneur.com/article/268104",
];

export default sources;
